services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile 경로 명시 (선택 사항이지만 명확함)
    container_name: rag_api_container
    ports:
      - "8282:8282"
    env_file:
      - .env
    depends_on:
      qdrant_db:
        condition: service_started
      redis_db:
        condition: service_started

  qdrant_db: # 서비스 이름을 qdrant에서 qdrant_db로 명시적으로 변경 (rag-api의 depends_on과 일관성)
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage # Qdrant 데이터의 지속성을 위해 볼륨 마운트
    container_name: qdrant_db

  redis_db:
    image: redis:latest # 공식 Redis 이미지 사용
    container_name: redis_db
    ports:
      - "6379:6379" # 로컬에서 Redis를 직접 확인하고 싶을 때 사용
    volumes:
      - ./redis_data:/data # Redis 데이터의 지속성을 위해 볼륨 마운트