services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_api_container
    ports:
      - "8282:8080"
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      qdrant_db:
        condition: service_started
      redis_db:
        condition: service_started
    networks: # ✨ 추가: 이 서비스가 사용할 네트워크 지정
      - my_rag_network # 정의할 네트워크 이름

  qdrant_db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    container_name: qdrant_db
    networks: # ✨ 추가: 이 서비스가 사용할 네트워크 지정
      - my_rag_network # 정의할 네트워크 이름

  redis_db:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks: # ✨ 추가: 이 서비스가 사용할 네트워크 지정
      - my_rag_network # 정의할 네트워크 이름

networks: # ✨ 추가: 네트워크 정의 섹션
  my_rag_network: # 네트워크 이름 (원하는 대로 변경 가능)
    driver: bridge # 기본 브릿지 네트워크 사용