services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile 경로 명시 (선택 사항이지만 명확함)
    container_name: rag_api_container
    ports:
      - "8282:8282"
    env_file:
      - .env
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma
    container_name: chromadb_server
    ports:
      - "8000:8000"
    volumes:
      # ChromaDB 데이터를 영구적으로 보존하기 위한 볼륨
      - chroma_server_data:/chroma
    # [수정] 공식 이미지의 실행 방식으로 변경
    command: run --host 0.0.0.0 --port 8000

volumes:
  chroma_server_data:
    driver: local